// <auto-generated />
namespace Partosazancnc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _9803266 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_9803266));
        
        string IMigrationMetadata.Id
        {
            get { return "201906160716506_9803266"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
