// <auto-generated />
namespace Partosazancnc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _980322 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_980322));
        
        string IMigrationMetadata.Id
        {
            get { return "201906120516423_980322"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
